Config temp changes

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,67 +1,81 @@
-version: 2
+#######################
+# WORKFLOWS DEFINITION
+#######################
+parameters:
+  run_main:
+    description: "runs the main gatekeeper job"
+    type: boolean
+    default: true
+  service1:
+    description: "runs specifically Service 1"
+    type: boolean
+    default: false
+  service2:
+    description: "runs specifically Service 2"
+    type: boolean
+    default: false
+
+workflows:
+  version: 2
+  primary: # Always triggers by default
+    when: << pipeline.parameters.run_main >>
+    jobs:
+      - build:
+          paths: |
+            service1
+            service2
+
+  service_1:
+    when: << pipeline.parameters.service1 >>
+    jobs:
+      - service1
+
+  service_2:
+    when: << pipeline.parameters.service2 >>
+    jobs:
+      - service2
+
+##################
+# JOBS DEFINITION
+##################
+version: 2.1
 jobs:
   build:
     docker:
       - image: circleci/golang
+    working_directory: ~/circleci-monorepo
+    parameters:
+      paths:
+        description: "Folder paths to check for changes. Should match workflow boolean flags"
+        type: string
     steps:
       - checkout
       - run:
-          name: Determine which projects have changed and trigger the builds
+          name: Determine which projects have changed and make API call accordingly
           command: |
-            # Identify modified directories
+            upstream="$(git merge-base HEAD origin/master)"
+            echo "Comparing to upstream commit $upstream"
 
-            LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH?filter=completed&limit=1"
-            LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'`
-
-            #first commit in a branch
-            if [[ ${LAST_SUCCESSFUL_COMMIT} == "null" ]]; then
-              COMMITS="origin/master"
-            else
-              COMMITS="${CIRCLE_SHA1}..${LAST_SUCCESSFUL_COMMIT}"
+            if [[ -z "$upstream" ]]; then
+              echo "git merge-base failed"
+              exit 1
+            fi
+  
+            # Print the diff
+            PAGER=cat git diff --stat=80 $upstream -- << parameters.paths >>
+  
+            # Halt if no diff
+            if git diff --quiet $upstream -- << parameters.paths >>; then
+              echo "Skipping job, no files modified"
+              circleci-agent step halt
             fi
 
-            git diff --name-only $COMMITS | cut -d/ -f1 | sort -u > projects
-            echo -e "Modified directories:\n`cat projects`\n"
+            echo << parameters.paths >>
+            # Iterate through paths
+            #    curl -s -u ${CIRCLE_TOKEN}: \
+            #      -d build_parameters[CIRCLE_JOB]=${project} \
+            #     https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
 
-
-            # If modified directories contain Gopkg/vendor directores, build all projects and exit
-            buildall=0
-            for project in `cat projects`; do
-              if [[ ${project} =~ "Gopkg" || ${project} =~ "vendor" ]]; then
-                buildall=1
-                echo -e "Dependencies change detected. building all $CIRCLE_PROJECT_REPONAME"
-                curl -s -u ${CIRCLE_TOKEN}: \
-                    -d build_parameters[CIRCLE_JOB]=all \
-                    https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
-              fi
-              if [[ ${buildall} -eq 1 ]]; then
-                exit 0
-              fi
-            done
-
-            # Build affected projects and their dependencies
-
-            projects_inc_dep=(`cat projects`)
-            echo -e "Calculating dependencies\n"
-            for dir in `ls -d */`; do
-              for dep in `go list -f '{{ .Deps }}' ./${dir} 2>/dev/null`; do
-                for project_dep in `echo $dep | grep github.com/tufin/$CIRCLE_PROJECT_REPONAME | egrep -v "vendor|${dir%\/}"`; do
-                  if [[ " ${projects_inc_dep[@]} " =~ " ${project_dep##*\/} " ]] && ! [[ " ${projects_inc_dep[@]} " =~ " ${dir%\/} " ]]; then
-                    projects_inc_dep+=(${dir%\/})
-                  fi
-                done
-              done
-            done
-
-            echo -e "Building: ${projects_inc_dep[@]}\n"
-            for project in ${projects_inc_dep[@]}; do
-              if grep -Fxq $project project-dirs; then
-                printf "\nTriggerring build for project: "$project
-                curl -s -u ${CIRCLE_TOKEN}: \
-                  -d build_parameters[CIRCLE_JOB]=${project} \
-                  https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
-              fi
-            done
   service1:
     working_directory: /go/src/github.com/tufin/circleci-monorepo
     docker:
@@ -106,3 +120,4 @@ jobs:
           destination: raw-test-output
       - store_test_results:
           path: /tmp/test-results
+
